### ISSUE TITLE
Internal work array size computation failed: -5

### ISSUE THREAD

**Issue by EricStarer** [cvlab-stonybrook/SID#12]
when I compute param, I met this error, could you give me some help? cause I can't go on.
```
Intel MKL ERROR: Parameter 5 was incorrect on entry to DGESDD.
Traceback (most recent call last):
  File "data_processing/compute_params.py", line 89, in <module>
    Rpopt, pcov = curve_fit(relit, R_s, R_t,bounds=c_bounds)
  File "/data1/xing_zhao/anaconda3/lib/python3.7/site-packages/scipy/optimize/minpack.py", line 764, in curve_fit
    _, s, VT = svd(res.jac, full_matrices=False)
  File "/data1/xing_zhao/anaconda3/lib/python3.7/site-packages/scipy/linalg/decomp_svd.py", line 125, in svd
    compute_uv=compute_uv, full_matrices=full_matrices)
  File "/data1/xing_zhao/anaconda3/lib/python3.7/site-packages/scipy/linalg/lapack.py", line 700, in _compute_lwork
    "%d" % (info,))
ValueError: Internal work array size computation failed: -5
```

**Comment by hieulem** [comment]
Hi @EricStarer ,

Please see below the list of dependencies:
[dependencies.txt](https://github.com/cvlab-stonybrook/SID/files/7117504/dependencies.txt)

**Comment by smoharana-1** [comment]
solve this problem
